server:
  port: 8082
cas:
#  cas服务端地址
  server-url-prefix: http://localhost:8091/cas
#  cas服务端的登陆地址
  server-login-url: http://localhost:8091/cas/login
#  当前客户端地址
  client-host-url: http://localhost:8082
#  Ticket校验器
  validation-type: cas3